version: "3.7"
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:15.0.0
    ports:
      - "8888:8080"
    volumes:
      - "./keycloak/realm-export.json:/opt/jboss/import/realm-export.json"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://host.docker.internal:8888/auth
      - KEYCLOAK_IMPORT=/opt/jboss/import/realm-export.json
  keycloak-gatekeeper:
    container_name: keycloak-gatekeeper
    image: keycloak/keycloak-gatekeeper
    # entrypoint: 'sh -c "while :; do sleep 1; done"'
    command: ['--config', '/opt/config.yml']
    volumes:
      - ./keycloak-gatekeeper/config.yml:/opt/config.yml
    ports:
      - 3000:3000
    restart: always # restart it until our keycloak instance is up
    depends_on:
      - keycloak
      - app
  app:
    container_name: app
    image: wordpress
    ports:
      - 8880:80
